name: build

on: push

jobs:
  build:
    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: pip install -r requirements.txt pyinstaller

    - name: build .app using pyinstaller
      run: pyinstaller app-macos.spec

    - name: compress artifact
      run: (cd dist && zip -r cutter.app.zip cutter.app)

    - uses: actions/upload-artifact@v3
      with:
        name: cutter.app.zip
        path: dist/cutter.app.zip
